### ISSUE TITLE
Remove config-generator dependency

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-helm-charts#3]
Currently the helm-charts utilise the Infinispan image `IDENTITIES_PATH` and `CONFIG_PATH` env variables to configure the underlying server. We should remove this in favour of generating the Infinispan xml directly and adding users via the cli.

**Comment by dmvolod** [comment]
@ryanemerson do you plan to implement this option in the operator?

**Comment by ryanemerson** [comment]
Yes. Long term we want to remove the need for the config-generator entirely.
