### ISSUE TITLE
Main service as headless if using ClusterIP

### ISSUE THREAD

**Issue by nicknas** [infinispan/infinispan-helm-charts#72]
When using ClusterIP, it only provides one record of the server to the client. When using LoadBalancer or a headless service in a Statefulset, the client could receive all the records for every replica inside the server. Using a headed clusterIP service, the client will only receive one of the multiple replicas on every client request.

**Comment by rigazilla** [comment]
sorry I'm little late...

There's already an headless service for this purpose: `infinispan-ping`. Can't we just rely on that one for this use case?

**Comment by rigazilla** [comment]
how to get full IP addresses list is in #88
