### ISSUE TITLE
Not able to deploy to EKS becuase of kubeVersion comparison

### ISSUE THREAD

**Issue by preetsindhal** [infinispan/infinispan-helm-charts#79]
Error:
Helm install failed: chart requires `kubeVersion: >= 1.21.0` which is incompatible with Kubernetes `v1.24.13-eks-0a21954`

Fix:
I tested it can be fixed by adding `kubeVersion: >= 1.21.0-0` but not sure if it works well with non EKS clusters.

https://github.com/helm/helm/issues/10375

Thanks.

**Comment by ryanemerson** [comment]
Fixed. Thanks for raising the issue @preetsindhal

**Comment by preetsindhal** [comment]
> Fixed. Thanks for raising the issue @preetsindhal

Thanks for quick response and fix.
