### ISSUE TITLE
ability to specify nodeSelector for infinispan

### ISSUE THREAD

**Issue by makdeniss** [infinispan/infinispan-helm-charts#83]
Is there an ability to specify `nodeSelector` in value.yaml for infinispan chart?

**Comment by ryanemerson** [comment]
Yes. A user contributed that recently https://github.com/infinispan/infinispan-helm-charts/commit/02eafe2bb5492f82dfa9ca86b738525c57da472e. This isn't included in a release though ... I'll release 0.3.2 with the addition.

**Comment by ryanemerson** [comment]
The chart should be available to consume once https://github.com/openshift-helm-charts/charts/pull/920 has been merged.

**Comment by makdeniss** [comment]
@ryanemerson is there a workaround for this I can use currently, or its worth waiting for the above PR to be merged and released? Is this going to take a lot of time?

**Comment by ryanemerson** [comment]
@makdeniss The last release took about a week to be merged. I can try to expedite this on my side, but it's not as quick as it should be unfortunately.

In the meantime you can just clone the repository locally and use the chart directly.

**Comment by makdeniss** [comment]
@ryanemerson 
> The last release took about a week to be merged. I can try to expedite this on my side, but it's not as quick as it should be unfortunately.
Please do, I would like to avoid doing workarounds as much as possible. 
> In the meantime you can just clone the repository locally and use the chart directly.
Will try that in the meantime.

**Comment by ryanemerson** [comment]
@makdeniss Chart 0.3.2 has been released
