### ISSUE TITLE
How to safely add password to security.batch

### ISSUE THREAD

**Issue by oburd** [infinispan/infinispan-helm-charts#90]
Hello!
I have a question about how to safely add password to security.batch through values.yml ?
Because in documantation only showing this
deploy:
  security:
    batch: 'user create admin -p changeme'

Because i dont see how it's possible to add now.
only one thing come it's doing from --set deploy.security.batch="user create admin -p ${var.password}"
Is this work for me ?
Thank you

**Comment by ryanemerson** [comment]
Instead of using `deploy.security.batch`, you can provide all of the values via a k8s Secret defined at `deploy.security.secretName`:

https://infinispan.org/docs/helm-chart/main/helm-chart.html#adding-multiple-credentials_configuring-authentication

**Comment by oburd** [comment]
well i'm using Terraform for deploy this
i have found another solution do it from unite locals and than add to set variable
