### ISSUE TITLE
Add volume without using TemplateVolume

### ISSUE THREAD

**Issue by oburd** [infinispan/infinispan-helm-charts#92]
Hello!
There is a question:
I saw that you are using volume Template, but is this possible using volume which already exist ?
I mean not create through volumeTemplate
Thank you

**Comment by ryanemerson** [comment]
Not with the current chart. We use `volumeClaimTemplates` as it ensures that a PVC is automatically created per StatefulSet replica as the cluster is scaled up.

Why do you want to use an existing volume with the cluster pods?

**Comment by oburd** [comment]
@ryanemerson well we have a efs-controller which create, and i scare that it's can create a lot of incorrect volumes which i dont need.
So as i correct understand i need to write a correct storageClass for creation volumes ?

**Comment by ryanemerson** [comment]
You can specify the `storageClassName` used by the PVC via the `deploy.container.storage.storageClassName` element.

**Comment by oburd** [comment]
Okay understood, thank you
